language:
    - python

os:
  # - windows # Python not supported yet for travis windows builds 12/11/2018
  - linux
  # - osx # Python not supported yet for travis osx builds 12/11/2018

python:
  - 3.6
  - 3.7
  - 3.8

services:
  - docker

before_install:
    # install node using this guide https://github.com/nvm-sh/nvm
    # install node version manager
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
    - source ~/.profile
    - nvm install stable
    - nvm use stable
    # check node version (for debuggin)
    - node -v

install:
  # install imagepypelines-tools
  - pip install .

  # build the dashboard files
  # install node
  - cd ip-client
  - npm i
  - ./node_modules/.bin/ng build --prod

script:
  # license enforcer
  # - python enforcer.py

  # run tests
  # - py.test 

  # build the docker dashboard image
  - imagepypelines build

  # test the dashboard
  # ...
  # ...
  # ...


after_success:
  # logging into docker
  - echo "$DOCKER_PASS" | docker login -u jmaggio14 --password-stdin

  # upload docker images to dockerhub
deploy:
  provider: script
  script: bash imagepypelines push
  on:
    branch: master
    tags: true
